spring.application.name=fawry

management.otlp.metrics.export.url=http://localhost:4318/v1/metrics
management.opentelemetry.tracing.export.otlp.endpoint=http://localhost:4318/v1/traces
management.opentelemetry.logging.export.otlp.endpoint=http://localhost:4318/v1/logs
management.tracing.sampling.probability=1.0

#db connection
spring.datasource.url=jdbc:postgresql://localhost:5433/travelDestinationPlanner
spring.datasource.username=travelDestinationPlanner
spring.datasource.password=travelDestinationPlanner
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=30000


# jwt
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970